Repository CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15, pull requests merged in 2020-10, with the labels that each got.

#10 feat: add CRUD functionalities for questions
  server/package.json
  server/src/controllers/questions.ts
  server/src/middlewares/customErrorHandler.ts
  server/src/models/Answer.ts
  server/src/models/Question.ts
  server/src/models/User.ts
  server/src/models/Util.ts
  server/src/routes/questions.ts
  server/src/services/database.ts
  server/src/services/server.ts
  server/src/utils/HttpStatusCode.ts
  server/src/utils/errors/ApiError.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/tests/routes/questions.test.ts
  server/tests/services/database.test.ts
  server/yarn.lock
Labels: status: completed, type: feature

#19 docs: add answers api reference for server
  README.md
Labels: status: completed, type: docs

#16 server: update database schema
  server/src/controllers/questions.ts
  server/src/models/Answer.ts
  server/src/models/Question.ts
  server/src/models/Vote.ts
  server/src/models/index.ts
  server/src/utils/constants.ts
Labels: priority: high, status: completed, type: feature

#22 server: update questions API to accommodate new database schema
  README.md
  server/package.json
  server/src/controllers/questions.ts
  server/src/routes/questions.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/src/utils/titleToSlug.ts
  server/tests/routes/questions.test.ts
  server/tests/utils/titleToSlug.test.ts
  server/yarn.lock
Labels: priority: high, status: completed, type: feature

#25 refactor: use camelCase instead of snake_case for JSON keys
  README.md
  server/src/controllers/questions.ts
  server/src/models/Answer.ts
  server/src/models/Question.ts
  server/src/models/User.ts
  server/src/models/Util.ts
  server/src/models/Vote.ts
  server/src/routes/questions.ts
Labels: status: completed, type: refactor

#32 fix: make API errors return json data to caller
  server/src/middlewares/customErrorHandler.ts
Labels: status: completed, type: feature

#29 feat: integrate with Firebase Auth
  .gitignore
  client/components/authentication/index.tsx
  client/package.json
  client/pages/_app.tsx
  client/pages/login/index.tsx
  client/pages/login/login.module.css
  client/pages/register/index.tsx
  client/pages/register/login.module.css
  client/yarn.lock
  server/package.json
  server/src/controllers/users.ts
  server/src/index.ts
  server/src/middlewares/authRouteHandler.ts
  server/src/models/User.ts
  server/src/routes/questions.ts
  server/src/routes/users.ts
  server/src/services/authentication.ts
  server/src/services/database.ts
  server/src/services/server.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/yarn.lock
Labels: priority: high, status: in progress, type: feature

#35 docs: update setup info and API ref for firebase auth
  README.md
Labels: status: completed, type: docs

#27 Eugene/setup fe Integrate with questions API
  .editorconfig
  README.md
  client/.eslintrc.json
  client/.prettierrc
  client/components/api/index.ts
  client/components/api/questions.ts
  client/components/authentication/index.tsx
  client/components/landing/index.tsx
  client/components/landing/landing.module.css
  client/components/layout/Layout.module.css
  client/components/layout/index.tsx
  client/components/questions/ask-question.tsx
  client/components/questions/index.tsx
  client/components/questions/question.module.css
  client/components/questions/render-markdown-editor.tsx
  client/components/questions/render-markdown-viewer.tsx
  client/components/questions/view-question.tsx
  client/jest.config.js
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/app.css
  client/pages/forum/forum.module.css
  client/pages/forum/index.tsx
  client/pages/index.tsx
  client/pages/landing/index.tsx
  client/pages/login/index.tsx
  client/pages/question/[qid].tsx
  client/pages/question/ask.tsx
  client/pages/question/index.tsx
  client/pages/register/index.tsx
  client/pages/user/[uid].tsx
  client/pages/user/index.tsx
  client/test/__mocks__/fileMock.js
  client/test/pages/index.test.tsx
  client/test/testUtils.ts
  client/tsconfig.json
  client/util/HttpStatusCode.ts
  client/util/convertor.ts
  client/util/index.ts
  client/util/mock.ts
  client/util/page-title.ts
  client/util/routes.ts
  client/util/types.ts
  client/yarn.lock
Labels: priority: high, status: completed, type: feature

#38 Server: merge missing commits from auth integration
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/middlewares/authRouteHandler.ts
  server/src/routes/questions.ts
Labels: priority: high, status: completed, type: feature

#37 Chore: fix development environment
  .vscode/settings.json
  client/.eslintrc.js
  client/.prettierrc
  client/.prettierrc.js
  client/package.json
  client/yarn.lock
Labels: status: completed, type: chore

#24 Answers CRUD
  README.md
  client/pages/_app.tsx
  client/pages/register/index.tsx
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/routes/answers.ts
  server/src/services/database.ts
  server/src/services/server.ts
  server/src/utils/errors/ApiErrorMessage.ts
Labels: priority: high, status: in progress, type: feature

#44 refactor: change all usage of deprecated `ObjectID` to `ObjectId`
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/routes/answers.ts
  server/src/routes/questions.ts
  server/src/routes/users.ts
  server/tests/routes/questions.test.ts
Labels: status: completed, type: refactor

#45 server: refactor questions API and directories
  server/package.json
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/middlewares/authRouteHandler.ts
  server/src/middlewares/customErrorHandler.ts
  server/src/models/Question.ts
  server/src/routes/answers.ts
  server/src/routes/questions.ts
  server/src/routes/users.ts
  server/src/utils/constants.ts
  server/src/utils/constants/HttpStatusCode.ts
  server/src/utils/constants/Level.ts
  server/src/utils/constants/Subject.ts
  server/src/utils/constants/VoteType.ts
  server/src/utils/constants/index.ts
  server/src/utils/errors/ApiError.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/src/utils/errors/index.ts
  server/src/utils/helpers/index.ts
  server/src/utils/helpers/titleToSlug.ts
  server/src/utils/helpers/toValidObjectId.ts
  server/src/utils/index.ts
  server/src/utils/types/QuestionRequestBody.ts
  server/src/utils/types/index.ts
  server/tests/routes/questions.test.ts
  server/tests/utils/titleToSlug.test.ts
Labels: status: completed, type: refactor

#47 refactor: shift error handling from users route to controller
  server/src/controllers/users.ts
  server/src/routes/users.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/src/utils/types/UserRequestBody.ts
  server/src/utils/types/index.ts
Labels: status: completed, type: refactor

#49 server: fix users endpoint and add bypass auth option for dev env
  README.md
  server/package.json
  server/src/index.ts
  server/src/middlewares/authRouteHandler.ts
  server/src/routes/users.ts
Labels: status: completed, type: feature

#46 server: fix and add tests
  codecov.yml
  server/jest.config.js
  server/src/controllers/users.ts
  server/src/middlewares/authRouteHandler.ts
  server/src/routes/users.ts
  server/src/utils/constants/TestConfig.ts
  server/src/utils/constants/index.ts
  server/tests/controllers/questions.test.ts
  server/tests/controllers/users.test.ts
  server/tests/middlewares/authRouteHandler.test.ts
  server/tests/middlewares/customErrorHandler.test.ts
  server/tests/routes/questions.test.ts
  server/tests/services/database.test.ts
  server/tests/utils/index.test.ts
  server/tests/utils/titleToSlug.test.ts
Labels: priority: medium, status: completed, type: test

#51 server: refactor environment variables and add assertions
  server/src/middlewares/authRouteHandler.ts
  server/src/services/authentication.ts
  server/src/services/database.ts
  server/src/utils/helpers/envUtils.ts
  server/src/utils/helpers/index.ts
  server/tests/index.test.ts
  server/tests/services/database.test.ts
  server/tests/utils/envUtils.test.ts
  server/tests/utils/index.test.ts
  server/tests/utils/titleToSlug.test.ts
  server/tests/utils/toValidObjectId.test.ts
Labels: status: completed, type: refactor

#48 refactor: shift error handling to answer controller
  server/src/controllers/answers.ts
  server/src/models/Answer.ts
  server/src/routes/answers.ts
  server/src/utils/types/AnswerRequestBody.ts
  server/src/utils/types/index.ts
Labels: priority: critical, status: completed, type: refactor

#53 chore: rimraf dist when using dev or start commands
  server/package.json
  server/yarn.lock
Labels: status: completed, type: chore

#54 refactor: check validity of uid in auth middleware
  server/src/middlewares/authRouteHandler.ts
  server/src/routes/questions.ts
  server/tests/middlewares/authRouteHandler.test.ts
Labels: status: completed, type: refactor

#40 Feat:user page, integration with authentication api
  client/.babelrc
  client/components/api/index.ts
  client/components/api/questions.ts
  client/components/api/user.ts
  client/components/api/util.ts
  client/components/authentication/index.tsx
  client/components/layout/Layout.module.css
  client/components/layout/index.tsx
  client/components/questions/ask-question.tsx
  client/components/questions/render-markdown-editor.tsx
  client/components/questions/render-markdown-viewer.tsx
  client/components/questions/view-question.tsx
  client/components/user/index.tsx
  client/components/user/user.module.css
  client/next.config.js
  client/package.json
  client/pages/404.tsx
  client/pages/_app.tsx
  client/pages/antd.less
  client/pages/app.css
  client/pages/firebase.config.ts
  client/pages/forum/index.tsx
  client/pages/login/login.module.css
  client/pages/question/[qid].tsx
  client/pages/register/index.tsx
  client/pages/user/[uid].tsx
  client/util/HttpStatusCode.ts
  client/util/index.ts
  client/util/mock.ts
  client/util/routes.ts
  client/util/types.ts
  client/yarn.lock
  server/src/controllers/users.ts
  server/src/routes/users.ts
Labels: priority: high, status: completed, type: feature

#58 chore: update vsc settings to auto fix eslint errors on save
  .vscode/settings.json
Labels: status: completed, type: chore

#57 Feat question integration
  README.md
  client/components/api/questions.ts
  client/components/api/user.ts
  client/components/api/util.ts
  client/components/authentication/index.tsx
  client/components/layout/index.tsx
  client/components/questions/ask-question.tsx
  client/components/questions/view-question.tsx
  client/pages/forum/forum.module.css
  client/pages/forum/index.tsx
  client/pages/landing/index.tsx
  client/pages/login/index.tsx
  client/pages/question/[qid].tsx
  client/pages/question/ask.tsx
  client/pages/user/[uid].tsx
  client/pages/user/index.tsx
  client/util/routes.ts
  client/util/types.ts
Labels: priority: medium, status: completed, type: feature

#52 feat: Auth and User Integration for Answers
  README.md
  server/package.json
  server/src/controllers/answers.ts
  server/src/controllers/users.ts
  server/src/models/Answer.ts
  server/src/routes/answers.ts
  server/yarn.lock
Labels: priority: high, status: completed, type: feature

#61 Feat: added pagination to server
  README.md
  server/src/controllers/questions.ts
  server/src/routes/questions.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/src/utils/types/GetQuestionRequestResponse.ts
  server/tests/controllers/questions.test.ts
  server/tests/routes/questions.test.ts
Labels: priority: medium, status: completed, type: feature

#64 client: Feat integrate pagination
  client/components/api/questions.ts
  client/components/api/util.ts
  client/package.json
  client/pages/forum/index.tsx
  client/util/types.ts
  client/yarn.lock
Labels: priority: medium, status: completed, type: feature

#63 client: refactor and rework question page
  client/components/questions/ask-question.tsx
  client/components/questions/index.tsx
  client/components/questions/question-form.tsx
  client/components/questions/question.module.css
  client/components/questions/render-markdown-editor.tsx
  client/components/questions/render-markdown-viewer.tsx
  client/components/questions/view-answers.tsx
  client/components/questions/view-question-preview.tsx
  client/components/questions/view-question.tsx
  client/config/firebase.config.ts
  client/next.config.js
  client/package.json
  client/pages/404/index.tsx
  client/pages/_app.tsx
  client/pages/forum/index.tsx
  client/pages/question/[qid].tsx
  client/pages/question/[qid]/[slug]/edit/index.tsx
  client/pages/question/[qid]/[slug]/index.tsx
  client/pages/question/[qid]/index.tsx
  client/pages/question/ask.tsx
  client/pages/question/ask/index.tsx
  client/pages/question/index.tsx
  client/pages/question/question.module.css
  client/styles/antd.less
  client/styles/app.css
  client/styles/global.css
  client/styles/markdown.css
  client/tsconfig.json
  client/util/date-utils.ts
  client/util/index.ts
  client/util/markdown-to-react-node.ts
  client/util/mock.ts
  client/util/routes.ts
  client/util/types.ts
  client/yarn.lock
Labels: priority: high, status: completed, type: feature

#68 client: major refactor for code quality
  client/components/api/questions.ts
  client/components/api/user.ts
  client/components/api/util.ts
  client/components/authentication/index.tsx
  client/components/landing/index.tsx
  client/components/layout/index.tsx
  client/components/questions/AnswerPreview.tsx
  client/components/questions/QuestionForm.tsx
  client/components/questions/QuestionPreview.tsx
  client/components/questions/ViewAnswersCard.tsx
  client/components/questions/ViewQuestionCard.tsx
  client/components/questions/index.module.css
  client/components/questions/index.tsx
  client/components/user/index.tsx
  client/pages/404/index.tsx
  client/pages/_app.tsx
  client/pages/forum/index.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/question/[qid]/[slug]/edit/index.tsx
  client/pages/question/[qid]/[slug]/index.tsx
  client/pages/question/[qid]/index.tsx
  client/pages/question/ask/index.tsx
  client/pages/register/index.tsx
  client/pages/user/[uid].tsx
  client/test/pages/index.test.tsx
  client/util/convertor.ts
  client/util/index.ts
  client/util/page-title.ts
  client/util/routes.ts
  client/utils/api/index.ts
  client/utils/api/questions.ts
  client/utils/api/user.ts
  client/utils/api/util.ts
  client/utils/constants/NavMenuKey.ts
  client/utils/constants/PageTitle.ts
  client/utils/constants/Route.ts
  client/utils/constants/index.ts
  client/utils/helpers/dateUtils.ts
  client/utils/helpers/firebaseAuthUtils.ts
  client/utils/helpers/index.ts
  client/utils/helpers/markdownToReactNode.ts
  client/utils/index.ts
  client/utils/mock.ts
  client/utils/types/apiReqRes.ts
  client/utils/types/index.ts
  client/utils/types/models.ts
Labels: priority: high, status: completed, type: refactor

#69 Server: upvote downvote api
  README.md
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/controllers/votes.ts
  server/src/models/Vote.ts
  server/src/routes/questions.ts
  server/src/services/database.ts
  server/src/utils/types/GetQuestionRequestResponse.ts
  server/src/utils/types/QuestionRequestBody.ts
  server/tests/controllers/questions.test.ts
  server/tests/controllers/votes.test.ts
  server/tests/routes/questions.test.ts
  server/tests/services/database.test.ts
Labels: priority: high, status: completed, type: feature

#72 Server: upvote downvote api
  README.md
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/controllers/votes.ts
  server/src/routes/questions.ts
  server/src/services/database.ts
  server/src/utils/constants/VoteType.ts
  server/src/utils/types/GetQuestionRequestResponse.ts
  server/src/utils/types/Vote.ts
  server/src/utils/types/index.ts
  server/tests/controllers/questions.test.ts
  server/tests/controllers/votes.test.ts
  server/tests/routes/questions.test.ts
  server/tsconfig.build.json
  server/tsconfig.json
Labels: priority: high, status: completed, type: refactor

#73 fix: unsubscribe from listener after firebase user is resolved to prevent memory leak
  client/utils/helpers/firebaseAuthUtils.ts
Labels: status: completed, type: fix

#75 client: integrate with answers API
  README.md
  client/components/questions/AnswerForm.tsx
  client/components/questions/AnswerPreview.tsx
  client/components/questions/ViewAnswersCard.tsx
  client/components/questions/ViewAnswersCardListItem.tsx
  client/components/questions/index.module.css
  client/pages/question/[qid]/[slug]/index.tsx
  client/utils/api/answers.ts
  client/utils/api/index.ts
  client/utils/types/apiReqRes.ts
  client/utils/types/models.ts
  server/src/routes/answers.ts
Labels: priority: high, status: completed, type: feature

#71 server: dealing with answers of deleted question
  server/src/controllers/answers.ts
  server/src/controllers/users.ts
  server/src/routes/questions.ts
Labels: priority: high, status: in progress

#77 client: protected route
  client/components/layout/index.tsx
  client/components/questions/QuestionForm.tsx
  client/pages/_app.tsx
  client/pages/question/[qid]/[slug]/edit/index.tsx
Labels: priority: low, status: completed, type: feature

#79 fix: conditionally render create answer form based on auth
  client/components/questions/ViewAnswersCard.tsx
  client/components/questions/ViewAnswersCardListItem.tsx
Labels: status: completed, type: fix

#80 server: add user endpoints
  README.md
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/routes/users.ts
Labels: priority: high, status: completed, type: feature

#82 Server: refactor types to better names and directories
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/controllers/votes.ts
  server/src/routes/answers.ts
  server/src/routes/questions.ts
  server/src/routes/users.ts
  server/src/utils/types/AnswerRequestBody.ts
  server/src/utils/types/GetQuestionRequestResponse.ts
  server/src/utils/types/QuestionRequestBody.ts
  server/src/utils/types/UserRequestBody.ts
  server/src/utils/types/Vote.ts
  server/src/utils/types/answerTypes.ts
  server/src/utils/types/index.ts
  server/src/utils/types/questionTypes.ts
  server/src/utils/types/userTypes.ts
  server/src/utils/types/voteTypes.ts
  server/tests/controllers/questions.test.ts
  server/tests/routes/questions.test.ts
Labels: status: completed, type: refactor

#81 client: integerate upvote downvote
  client/components/questions/QuestionPreview.tsx
  client/components/questions/UpvoteDownvote.tsx
  client/components/questions/index.module.css
  client/components/questions/index.tsx
  client/components/user/index.tsx
  client/pages/question/[qid]/[slug]/index.tsx
  client/utils/api/questions.ts
  client/utils/constants/index.ts
  client/utils/constants/voteType.ts
  server/src/controllers/questions.ts
  server/src/routes/questions.ts
  server/tests/controllers/questions.test.ts
Labels: priority: high, status: in progress, type: feature

#76 Server chore: Updated Level and Subjects Enum
  server/src/utils/constants/Level.ts
  server/src/utils/constants/Subject.ts
Labels: priority: medium, status: completed, type: chore

#84 Client: custom hook for upvote downvote
  client/components/questions/UpvoteDownvote.tsx
  client/utils/hooks/index.ts
  client/utils/hooks/useUpvoteDownvote.ts
  server/src/controllers/questions.ts
Labels: priority: medium, status: completed, type: fix, type: refactor

#83 server: answers vote API
  README.md
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/users.ts
  server/src/controllers/votes.ts
  server/src/middlewares/customErrorHandler.ts
  server/src/models/Vote.ts
  server/src/routes/answers.ts
  server/src/routes/questions.ts
  server/src/services/authentication.ts
  server/src/services/database.ts
  server/src/utils/constants/VoteType.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/src/utils/types/questionTypes.ts
  server/src/utils/types/voteTypes.ts
  server/tests/controllers/questions.test.ts
  server/tests/controllers/votes.test.ts
  server/tests/routes/answers.test.ts
  server/tests/routes/questions.test.ts
Labels: priority: high, status: in progress, type: feature

#86 Client: integrate with answers vote API
  client/components/authentication/index.tsx
  client/components/questions/AnswerForm.tsx
  client/components/questions/QuestionForm.tsx
  client/components/questions/QuestionUpvoteDownvote.tsx
  client/components/questions/ViewAnswersCard.tsx
  client/components/questions/ViewAnswersCardListItem.tsx
  client/components/questions/ViewQuestionCard.tsx
  client/components/questions/index.tsx
  client/utils/api/answers.ts
  client/utils/api/questions.ts
  client/utils/api/util.ts
  client/utils/constants/voteType.ts
  client/utils/helpers/firebaseAuthUtils.ts
  client/utils/hooks/useUpvoteDownvote.ts
  client/utils/index.ts
  client/utils/types/apiReqRes.ts
Labels: priority: high, status: completed, type: feature

#87 Fuzzy search
  server/src/controllers/questions.ts
  server/src/services/database.ts
  server/src/utils/types/questionTypes.ts
Labels: priority: medium, status: in progress, type: feature

#92 misc additions
  client/components/landing/index.tsx
  client/components/landing/landing.module.css
Labels: priority: low, status: completed, type: chore

#96 docs: fix analytics api ref
  README.md
Labels: status: completed, type: docs

#98 server: Add sorting options to answers
  README.md
  server/src/controllers/answers.ts
  server/src/routes/answers.ts
  server/src/routes/questions.ts
Labels: status: completed

#99 server: deployment to GCP
  README.md
  server/cloudbuild.yaml
  server/package.json
  server/src/index.ts
  server/src/utils/helpers/envUtils.ts
  server/tests/controllers/questions.test.ts
  server/tests/controllers/users.test.ts
  server/tests/controllers/votes.test.ts
  server/tests/middlewares/authRouteHandler.test.ts
  server/tests/middlewares/customErrorHandler.test.ts
  server/tests/services/database.test.ts
  server/tests/utils/envUtils.test.ts
Labels: priority: high, status: completed, type: chore
