Repository CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15, pull requests merged in 2020-11, with the labels that each got.

#100 client: deployment to Vercel
  README.md
  client/test/__mocks__/fileMock.js
  client/test/pages/__snapshots__/index.test.tsx.snap
  client/test/pages/index.test.tsx
  client/test/testUtils.ts
  client/utils/api/util.ts
  client/utils/index.ts
  client/utils/mock.ts
Labels: priority: high, status: completed, type: chore

#106 server: Sort by upvotes if nett votes are the same
  server/src/controllers/answers.ts
Labels: status: completed, type: fix

#104 Client search functionality
  client/components/questions/QuestionForm.tsx
  client/components/util/FormLabel.tsx
  client/components/util/index.ts
  client/pages/forum/forum.module.css
  client/pages/forum/index.tsx
  client/utils/types/apiReqRes.ts
  server/src/controllers/questions.ts
  server/src/routes/questions.ts
  server/src/services/database.ts
  server/src/utils/types/questionTypes.ts
Labels: priority: high, status: completed, type: feature

#108 feat: support username and fix auth designs
  client/components/authentication/index.tsx
  client/components/landing/index.tsx
  client/components/landing/landing.module.css
  client/components/layout/Layout.module.css
  client/components/layout/index.tsx
  client/pages/404/index.tsx
  client/pages/login/index.tsx
  client/pages/login/login.module.css
  client/pages/register/index.tsx
  client/pages/user/[uid].tsx
  client/pages/user/[username].tsx
  client/utils/api/user.ts
  client/utils/types/apiReqRes.ts
  client/utils/types/models.ts
  server/src/controllers/users.ts
  server/src/routes/users.ts
  server/src/utils/errors/ApiErrorMessage.ts
  server/src/utils/types/userTypes.ts
Labels: status: completed, type: feature

#109 feat: support username and other design tweaks
  client/components/questions/AnswerForm.tsx
  client/components/questions/AnswerPreview.tsx
  client/components/questions/QuestionForm.tsx
  client/components/questions/QuestionPreview.tsx
  client/components/questions/QuestionUpvoteDownvote.tsx
  client/components/questions/ViewAnswersCard.tsx
  client/components/questions/ViewAnswersCardListItem.tsx
  client/components/questions/ViewQuestionCard.tsx
  client/components/questions/index.tsx
  client/pages/forum/forum.module.css
  client/pages/forum/index.tsx
  client/pages/question/[qid]/[slug]/index.tsx
  client/utils/api/answers.ts
  client/utils/api/questions.ts
  client/utils/types/apiReqRes.ts
  client/utils/types/models.ts
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/routes/answers.ts
  server/src/routes/questions.ts
  server/src/utils/types/answerTypes.ts
  server/src/utils/types/questionTypes.ts
  server/tests/controllers/questions.test.ts
Labels: priority: high, status: completed, type: feature

#110 fix: hot fixes for prod release
  client/components/authentication/index.tsx
  client/components/questions/QuestionForm.tsx
  client/pages/question/[qid]/[slug]/edit/index.tsx
  server/src/utils/helpers/envUtils.ts
Labels: status: completed, type: fix

#111 fix: minor typo
  client/components/questions/AnswerForm.tsx
  client/components/questions/QuestionForm.tsx
  client/components/questions/ViewAnswersCardListItem.tsx
  client/components/questions/ViewQuestionCard.tsx
Labels: status: completed, type: fix

#105 server feat: analytics
  server/src/controllers/analytics.ts
  server/src/routes/analytics.ts
  server/src/services/server.ts
  server/src/utils/types/analyticsTypes.ts
Labels: priority: high, status: in progress, type: feature

#112 fix user fetching and layout
  client/components/user/index.tsx
  client/pages/forum/index.tsx
  client/pages/question/ask/index.tsx
  client/pages/user/[username].tsx
  client/utils/api/user.ts
  client/utils/api/util.ts
  client/utils/types/apiReqRes.ts
  client/utils/types/models.ts
  server/src/routes/analytics.ts
Labels: priority: high, status: completed

#118 fix: increase layout header z-index to 50
  client/components/layout/index.tsx
Labels: status: completed, type: fix

#119 Client: fix misc
  client/pages/question/ask/index.tsx
  client/utils/types/models.ts
Labels: priority: high, type: bug

#123 Docs: fix API references
  README.md
  client/README.md
  server/README.md
Labels: status: completed, type: docs

#121 full-document-return
  server/src/controllers/analytics.ts
  server/src/utils/types/analyticsTypes.ts
Labels: priority: high, status: completed, type: bug

#126 fixes for ad block
  README.md
  client/components/questions/ViewQuestionCard.tsx
  client/components/user/index.tsx
  client/pages/forum/index.tsx
  client/utils/api/util.ts
  client/utils/types/apiReqRes.ts
  server/src/services/server.ts
Labels: priority: high, status: completed, type: bug

#124 client: forum page redesign
  README.md
  client/components/questions/QuestionPreview.tsx
  client/pages/forum/index.tsx
  client/utils/types/apiReqRes.ts
  server/src/controllers/questions.ts
  server/src/utils/types/questionTypes.ts
Labels: priority: high, status: completed, type: feature

#127 server: get recently voted answers and questions
  server/src/controllers/analytics.ts
  server/src/controllers/answers.ts
  server/src/controllers/questions.ts
  server/src/controllers/votes.ts
  server/src/utils/types/analyticsTypes.ts
Labels: priority: high, status: completed, type: feature

#128 client: overall design tweaks
  client/components/landing/index.tsx
  client/components/landing/landing.module.css
  client/components/questions/AnswerPreview.tsx
  client/components/questions/QuestionPreview.tsx
  client/components/questions/ViewQuestionCard.tsx
  client/components/user/AnswerDisplay.tsx
  client/components/user/QuestionDisplay.tsx
  client/components/user/index.tsx
  client/pages/question/[qid]/[slug]/edit/index.tsx
  client/pages/question/ask/index.tsx
  client/pages/user/[username].tsx
  client/utils/helpers/dateUtils.ts
  client/utils/types/apiReqRes.ts
  server/src/controllers/analytics.ts
  server/src/utils/types/analyticsTypes.ts
  server/src/utils/types/index.ts
Labels: priority: high, status: in progress, type: feature, type: fix

#129 docs: fix client docs
  README.md
Labels: status: completed, type: docs
